# Gitleaks configuration for Claude Self-Reflect
# This file configures secret scanning to reduce false positives

[extend]
# Extend the base configuration
useDefault = true

# Allow specific commits with revoked keys
[[rules]]
id = "openai-api-key"
[rules.allowlist]
commits = ["39b40d74", "d21f2d07", "0003ad17", "cd159bde"]

[allowlist]
# Global allowlist configuration
description = "Allowlists for Claude Self-Reflect"

# Allow test and archived directories
paths = [
    '''test-.*\.js$''',
    '''test/.*''',
    '''tests/.*''',
    '''scripts/test/.*''',
    '''archived/.*''',
    '''claude-self-reflection/.*''',
    '''README\.md''',
    '''CLAUDE\.md''',
    '''docs/.*\.md''',
    '''installer/cli\.js''',
    '''installer/setup-wizard\.js''',
    '''.*\.example.*''',
    '''.*\.sample.*''',
    '''improved/.*''',
    '''\.env'''
]

# Allow specific patterns that are false positives
regexes = [
    '''pa-1234567890''',
    '''your-voyage-api-key''',
    '''YOUR_VOYAGE_KEY''',
    '''EXAMPLE_.*_KEY''',
    '''no API calls''',
    '''no API keys''',
    '''pa-wdTYGObaxhs-XFKX2r7WCczRwEVNb9eYMTSO3yrQhZI''',
    # Pattern to match revoked OpenAI keys in old commits
    '''sk-proj-[a-zA-Z0-9\-_]{130,150}'''
]