version: '3.8'

services:
  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant-storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  # Project-isolated importer service
  importer-isolated:
    build:
      context: .
      dockerfile: Dockerfile.importer-isolated
    container_name: importer-isolated
    depends_on:
      - qdrant
    volumes:
      - /Users/ramakrishnanannaswamy/.claude/projects:/logs:ro
      - ./config-isolated:/config
    environment:
      - QDRANT_URL=http://qdrant:6333
      - LOGS_DIR=/logs
      - STATE_FILE=/config/imported-files.json
      - ISOLATION_MODE=isolated
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - BATCH_SIZE=100
    restart: no

volumes:
  qdrant-storage: